### ISSUE TITLE
compiled error because of double_to_string changed

### ISSUE THREAD

**Issue by ktprime** [google/hashtable-benchmarks#14]
the lastest version

**Comment by fowles** [comment]
Fixed.  Right now you need to specify the cxxopt manually.  I intend to fix the crosstool file to make it work by default, but there you go.

bazel build --cxxopt='-std=c++17' :hashtable_benchmarks

**Comment by fowles** [comment]
48b5403f310e4e29c66a6f804a9479b2f4e8d5d8
