### ISSUE TITLE
bazel is awful

### ISSUE THREAD

**Issue by willy613** [google/hashtable-benchmarks#20]
Why can't you just use make like sane projects?

First issue, I forget the confusing error messages, but eventually I figured out that 'folly' has renamed its branch from master to main.  patch:

+++ b/WORKSPACE
@@ -59,8 +59,8 @@ http_archive(
 http_archive(
     name = "facebook_folly",
     build_file = "//:BUILD.folly",
-    strip_prefix = "folly-master",
-    urls = ["https://github.com/facebook/folly/archive/master.zip"],
+    strip_prefix = "folly-main",
+    urls = ["https://github.com/facebook/folly/archive/main.zip"],
 )
 
 # ska::flat_hash_set and ska::bytell_hash_set

Second issue:

ERROR: /home/willy/.cache/bazel/_bazel_willy/a2fc307a5e109a80523e72df06593c55/external/facebook_folly/BUILD.bazel:1:11: C++ compilation of rule '@facebook_folly//:folly' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 48 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/facebook_folly/folly/container/detail/F14Table.h:42,
                 from external/facebook_folly/folly/container/detail/F14Table.cpp:17:
external/facebook_folly/folly/functional/Invoke.h:22:10: fatal error: boost/preprocessor/control/expr_iif.hpp: No such file or directory
   22 | #include <boost/preprocessor/control/expr_iif.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //:hashtable_benchmarks failed to build

After trying a bunch of things, I decided to just "apt-get install libboost-all-dev"

Now I get a new error:
ERROR: /home/willy/.cache/bazel/_bazel_willy/a2fc307a5e109a80523e72df06593c55/external/facebook_folly/BUILD.bazel:1:11: undeclared inclusion(s) in rule '@facebook_folly//:folly':
this rule is missing dependency declarations for the following files included by 'external/facebook_folly/folly/lang/ToAscii.cpp':
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h'
Target //:hashtable_benchmarks failed to build

and I'm all out of spoons for debugging this.

**Comment by willy613** [comment]
Oh, good job github.  Why would anyone possibly want to paste a patch into an issue?  Far better to support markdown.  Yes, that's definitely the more important thing in an issue tracker.

**Comment by fowles** [comment]
Please maintain professional behavior and do not insult or demean the work of others when engaging with this project.
